# Generated by Django 6.0 on 2026-01-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_letter",
                    models.CharField(
                        help_text="Введите тему письма", verbose_name="Тема письма"
                    ),
                ),
                (
                    "body_letter",
                    models.TextField(
                        help_text="Содержание письма", verbose_name="Тело письма"
                    ),
                ),
            ],
        ),
    ]
