# Generated by Django 6.0 on 2026-01-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_recipient", "0001_initial"),
        ("message", "0001_initial"),
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="end_time",
            field=models.DateTimeField(verbose_name="Дата и время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="message.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="recipients",
            field=models.ManyToManyField(
                to="mail_recipient.recipient", verbose_name="Получатели"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="start_time",
            field=models.DateTimeField(verbose_name="Дата и время начало отправки"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                default="Создана", max_length=20, verbose_name="Статус"
            ),
        ),
    ]
