# Generated by Django 6.0 on 2026-01-15 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_alter_newsletter_start_time_alter_newsletter_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 15, 9, 44, 36, 995947, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время начало отправки",
            ),
        ),
    ]
